// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_APP_URL: string;
	NEXT_PUBLIC_TWITCH_CLIENT_ID: string;
	NEXT_PUBLIC_SUPABASE_PUBLIC_KEY: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	TWITCH_CLIENT_SECRET: string;
	TWITCH_SECRET: string;
}
