name = "nextjs-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run pages:build"
[build.upload]
format = "service-worker"

[site]
bucket = ".next/static"

[build.environment]
NODE_VERSION = "18" 